# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0003_auto_20181022_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='firstName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='lastName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
